
#ifndef _IR_PROTOCOL_DEF_H
#define _IR_PROTOCOL_DEF_H


enum IRPort{
    CmdPort = 56885,
    DataPort = 56886,
    SensorPort = 56887,
    DiscoverServerPort = 59101,
    DiscoverClientPort = 59100,
};

enum PackageType{
    CmdPackage = 1,
    ResponsePackage = 2,
    DataPackage = 3,
};

enum NetMainCmd{
    Y_NET_PROTOCOL = 0x01,
        Y_USE_TCP = 0x01,
        Y_USE_UDP = 0x02,
    Y_HARD_VERSION = 0x02,
        Y_GET_HARD_VERSION = 0X01,
    Y_IMG_SIZE = 0x03,
        Y_GTE_IMG_SIZE = 0x01,
        Y_SET_IMG_SIZE = 0x02,
        Y_GET_DET_IMG_SIZE = 0x03,
    Y_MAC_SERIAL = 0x04,
        Y_GET_MAC_SERIAL = 0x01,
    Y_CALIBRATE = 0x05,
        Y_CALIBRATE_MACHINE_TO_PC = 0x01,
    Y_TRANSFER = 0x06,
        Y_SEND_COR_STOP = 0x01,
        Y_SEND_COR_NOT_STOP = 0x02,
        Y_SEND_ORI_STOP = 0x03,
        Y_SEND_ORI_NOT_STOP = 0X04,
        Y_SEND_STOP = 0x05,
    Y_MAC_SHOW = 0x07,
        Y_SHOW_INFRAR = 0x01,
        Y_STOP_SHOW = 0x02,
    Y_RANGE_ACCURACY = 0x08,
        Y_SET_TEM_PRE = 0x01,
        Y_GET_TEM_PRE = 0x02,
        Y_UPDATE_TEM_PRE = 0x03,
    Y_GAIN = 0x09,
        Y_SET_GAIN = 0x01,
        Y_GET_GAIN = 0x02,
        Y_UPDATE_GAIN = 0x03,
    Y_OUTPUT_DATA_TYPE = 0x0A,
        Y_SET_OUTPUT_DATA_TYPE = 0x01,
        Y_GET_OUTPUT_DATA_TYPE = 0x02,
    Y_EDGE = 0x0B,
        Y_SET_LEFT_EDGE = 0x01,
        Y_SET_TOP_EDGE = 0x02,
        Y_GET_EDGE = 0x03,
    Y_CAPTURE_FREQ = 0x0C,
        Y_SET_CAPTURE_FREQ = 0x01,
        Y_GET_CAPTURE_FREQ = 0x02,
    Y_REVERSE_TYPE = 0x0D,
        Y_SET_REVERSE_TYPE = 0x01,
        Y_GET_REVERSE_TYPE = 0x02,
    Y_SENSOR_TEMP = 0x0E,
        Y_GET_1_SENSOR_TEMP = 0x01,
        Y_GET_2_SENSOR_TEMP = 0x02,
        Y_GET_3_SENSOR_TEMP = 0x03,
        Y_GET_4_SENSOR_TEMP = 0x04,
        Y_GET_MAC_COR_BENCH_TEMP = 0x05,
        Y_GET_SENSOR_TEMP_AND_BENCH_TEMP = 0xF0,
    Y_SHUTTER = 0x0F,
        Y_SHUTTER_UP = 0x01,
        Y_SHUTTER_DOWN = 0x02,
    Y_FOCUS = 0x10,
        Y_FOCUS_FAR = 0x01,
        Y_FOCUS_NER = 0x02,
        Y_FOCUS_SMALL_FAR = 0x03,
        Y_FOCUS_SMALL_NER = 0x04,
    Y_CORRECT = 0x11,
        Y_CORRECT_WITH_BAF = 0x01,
        Y_CORRECT_WTIHOUT_BAF = 0x02,
    Y_BAD_POINT = 0x012,
        Y_CONDUCT_BAD_POINT = 0x01,
        Y_NO_CONDUCT_BAD_POINT = 0x02,
        Y_ADD_BAD_POINT = 0x03,
        Y_DEL_BAD_POINT = 0x04,
        Y_SAVE_BAD_POINT = 0x05,
        Y_BAD_POINT_MACHINE_TO_PC = 0x06,
        Y_SET_BAD_POINT_ALG = 0x07,
        Y_GET_BAD_POINT_ALG = 0x08,
        Y_CLEAR_BAD_POINT = 0x09,
    Y_LEN = 0x13,
        Y_SET_LEN_TYPE = 0x01,
        Y_GET_LEN_TYPE = 0x02,
    Y_MEAS_GRADE = 0x14,
        Y_SET_MEAS_GRADE = 0x01,
        Y_GET_MEAS_GRADE = 0x02,
    Y_EMISS = 0x15,
        Y_SET_EMISS = 0x01,
        Y_GET_EMISS = 0x02,
    Y_DIST = 0x16,
        Y_SET_DIST = 0x01,
        Y_GET_DIST = 0x02,
    Y_ENV_TEMP = 0x17,
        Y_SET_ENV_TEMP = 0x01,
        Y_GET_ENV_TEMP = 0x02,
    Y_REL_HUM = 0x18,
        Y_SET_REL_HUM = 0x01,
        Y_GET_REL_HUM = 0x02,
    Y_MDF = 0x19,
        Y_SET_MDF = 0x01,
        Y_GET_MDF = 0x02,
    Y_TEMP_PARA = 0x1A,
        Y_SET_TEMP_PARA = 0x01,
        Y_GET_TEMP_PARA = 0x02,
    Y_TEMP_COMPENSATION = 0x1B,
        Y_SET_TEMP_COMPENSATION = 0x01,
        Y_GET_TEMP_COMPENSATION = 0x02,
    Y_INTEGRATION_TIME = 0x1C,
        Y_SET_INTEGRATION_TIME = 0x01,
        Y_GET_INTEGRATION_TIME = 0x02,
        Y_UPDATE_INTEGRATION_TIME = 0x03,
    Y_PARA_CONFIG = 0x1D,
        Y_SAVE_PARA_CONFIG = 0x01,
        Y_PARA_CONFIG_MACHINE_TO_PC = 0x02,
    Y_TWO_POINTS_CORRECT = 0x1E,
        Y_LOW_TEMP_TWO_POINTS_CORRECT = 0x01,
        Y_HIGH_TEMP_TWO_POINTS_CORRECT = 0x02,
        Y_SAVE_TWO_POINT = 0X03,
        Y_TWO_POINTS_MACHINE_TO_PC = 0x04,
    Y_DALASS_TEMP = 0x1F,
        Y_START_SEND_DALASS = 0x01,
        Y_STOP_SEND_DALASS = 0x02,

    Y_UPDATE_SOFE = 0xFF,
        Y_UPDATE_PC_TO_MACHINE = 0x01,
};

enum DataPack{
    Y_AD_DATA = 0x01,
        Y_AD_DATA_COR = 0x01,
        Y_AD_DATA_ORI = 0X02,
        Y_AD_DATA_ZIP_COR = 0X03,
        Y_AD_DATA_ZIP_ORG = 0X04,
  //  Y_SENSOR_TEMP = 0x0E,
        Y_SENSOR_TEMP_FOUR_COR_TEMP = 0x01,
//Y_LEN = 0x13,
        Y_DATA_LEN = 0x01,
    //Y_MEAS_GRADE = 0x14,
        Y_DATA_MEAS_GRADE = 0x01,
    //Y_EMISS = 0x15,
        Y_DATA_EMISS = 0x01,
    //Y_DIST = 0x16,
        Y_DATA_DIST = 0x01,
    //Y_ENV_TEMP = 0x17,
        Y_DATA_ENV_TEMP = 0x01,
    //Y_REL_HUM = 0x18,
        Y_DATA_REL_HUM = 0x01,
    //Y_MDF = 0x19,
        Y_DATA_MDF = 0x01,
    //Y_TEMP_PARA = 0x1A,
        Y_DATA_TEMP_PARA = 0x01,
    Y_LEVEL_SPAN = 0x1B,
        Y_DATA_LEVEL_SPAN = 0x01,
};

enum ResponseCode{
    SuccessResponse = 1,
    FailedResponse = 2,
};

#endif
